name: Question
description: Ask a question
title: "[QUESTION]: "
labels: ["question"]
assignees: ["AssigneeName"]
body:
  - type: textarea
    id: question-description
    attributes:
      label: Question
      description: Ask your question.
    validations:
      required: true
